version: '2'
services:
  web:
    build: .
    ports:
     - "3000:3000"
    volumes:
    - ".:/code"
    command: npm start
  redis:
    image: "redis:alpine"
    ports:
     - "6379:6379"
    volumes:
    - "./db:/data"
